# Generated by Django 6.0.4 on 2026-05-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resultposter_delete_country_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('US', 'US'), ('South Korea', 'South Korea'), ('UK', 'UK'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Europe', 'Europe')], max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='universities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
    ]
