# Generated by Django 6.0.4 on 2026-05-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
        migrations.AddField(
            model_name='university',
            name='qs_ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
