# Generated by Django 6.0.4 on 2026-05-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultposter',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='resultposter',
            name='name',
            field=models.CharField(default='Student', max_length=200),
        ),
        migrations.AddField(
            model_name='resultposter',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultposter',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resultposter',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
