# Generated by Django 6.0.4 on 2026-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_resultposter_options_resultposter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarship_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_max',
            field=models.PositiveIntegerField(blank=True, help_text='Annual tuition in USD (maximum)', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_min',
            field=models.PositiveIntegerField(blank=True, help_text='Annual tuition in USD (minimum)', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='university_type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10),
        ),
    ]
