# Generated by Django 6.0.4 on 2026-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_university_city_university_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='campus_tour_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube watch/share/embed link.'),
        ),
    ]
