# Generated by Django 6.0.4 on 2026-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, help_text='e.g. License, Contract, Partnership, Registration', max_length=120)),
                ('pdf', models.FileField(upload_to='certifications/')),
                ('preview_image', models.ImageField(blank=True, help_text='Auto-generated thumbnail of first page', null=True, upload_to='certifications/previews/')),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
