# Generated by Django 6.0.4 on 2026-06-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultposter',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='resultposter',
            name='country',
        ),
        migrations.RemoveField(
            model_name='resultposter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resultposter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resultposter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resultposter',
            name='order',
        ),
        migrations.RemoveField(
            model_name='resultposter',
            name='university',
        ),
    ]
